In [1]:
import numpy as np

In [2]:
# initiate variables
scalar1 = 1
scalar2 = 2
np_scalar1 = np.array(scalar1)
np_scalar2 = np.array(scalar2)

vector1 = [1, 2, 3, 4]
vector2 = [5, 6, 7, 8]
np_vector1 = np.array(vector1)
np_vector2 = np.array(vector2)

matrix1 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]
matrix2 = [
    [11, 12, 13, 14],
    [15, 16, 17, 18]
]
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

**ADD**

scalar + scalar

In [3]:
# numpy
np_res = np_scalar1 + np_scalar2

# python
py_res = scalar1 + scalar2

print(np_res, py_res)

3 3


scalar + vector

In [4]:
# numpy
np_res = np_scalar1 + np_vector1

# python
def matsum_vector_scalar(vector, scalar):
    return [v + scalar for v in vector]

py_res = matsum_vector_scalar(vector1, scalar1)

print(np_res, py_res)

[2 3 4 5] [2, 3, 4, 5]


scalar + matrix

In [5]:
# numpy
np_res = np_scalar1 + np_matrix1

# python
def matsum_matrix_scalar(matrix, scalar):
    return [[v + scalar for v in row] for row in matrix]

py_res = matsum_matrix_scalar(matrix1, scalar1)

print(np_res, py_res)

[[2 3 4 5]
 [6 7 8 9]] [[2, 3, 4, 5], [6, 7, 8, 9]]


vector + vector

In [6]:
# numpy
np_res = np_vector1 + np_vector2

# python
def matsum_vector_vector(vector_first, vector_second):
    result = []
    for v_f, v_s in zip(vector_first, vector_second):
        result.append(v_f + v_s)
    return result

py_res = matsum_vector_vector(vector1, vector2)

print(np_res, py_res)

[ 6  8 10 12] [6, 8, 10, 12]


vector + matrix

In [7]:
# numpy
np_res = np_vector1 + np_matrix1

# python
def matsum_vector_matrix(vector, matrix):
    result = []
    for row in matrix:
        tmp = []
        for vec, mat in zip(vector, row):
            tmp.append(vec + mat)
        result.append(tmp)
    return result

py_res = matsum_vector_matrix(vector1, matrix1)

print(np_res, py_res)

[[ 2  4  6  8]
 [ 6  8 10 12]] [[2, 4, 6, 8], [6, 8, 10, 12]]


matrix + matrix

In [8]:
# numpy
np_res = np_matrix1 + np_matrix2

# python
def matsum_matrix_matrix(matrix_first, matrix_second):
    result = []
    for i in range(len(matrix_first)):
        tmp = []
        for j in range(len(matrix_first[i])):
            tmp.append(matrix_first[i][j] + matrix_second[i][j])
        result.append(tmp)
    return result

py_res = matsum_matrix_matrix(matrix1, matrix2)

print(np_res, py_res)

[[12 14 16 18]
 [20 22 24 26]] [[12, 14, 16, 18], [20, 22, 24, 26]]


**MULTIPLY**

scalar * scalar

In [9]:
# numpy
np_res = np.dot(np_scalar1, np_scalar2)

# python
py_res = scalar1 * scalar2

print(np_res, py_res)

2 2


scalar * vector

In [10]:
# numpy
np_res = np.dot(np_scalar1, np_vector1)

# python
def matmul_vector_scalar(vector, scalar):
    return [v * scalar for v in vector]

py_res = matmul_vector_scalar(vector1, scalar1)

print(np_res, py_res)

[1 2 3 4] [1, 2, 3, 4]


scalar * matrix

In [11]:
# numpy
np_res = np.dot(np_scalar1, np_matrix1)

# python
def matmul_matrix_scalar(matrix, scalar):
    return [[v * scalar for v in row] for row in matrix]

py_res = matmul_matrix_scalar(matrix1, scalar1)

print(np_res, py_res)

[[1 2 3 4]
 [5 6 7 8]] [[1, 2, 3, 4], [5, 6, 7, 8]]


vector * vector

In [12]:
# numpy
np_res = np.dot(np_vector1, np_vector2)

# python
def matmul_vector_vector(vector_first, vector_second):
    result = 0
    for v_f, v_s in zip(vector_first, vector_second):
        result += v_f * v_s
    return result

py_res = matmul_vector_vector(vector1, vector2)

print(np_res, py_res)

70 70


vector * matrix

In [13]:
# numpy
np_res =  np.dot(np_matrix1, np_vector1)

#python
def matmul_vector_matrix(matrix, vector):
    result = []
    for row in matrix:
        tmp = 0
        for m_v, v in zip(row, vector):
            tmp += m_v * v
        result.append(tmp)
    return result

py_res = matmul_vector_matrix(matrix1, vector1)

print(np_res, py_res)

[30 70] [30, 70]


matrix * matrix

In [14]:
matrix1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
def transposition(matrix):
    matrixT = []
    for j in range(len(matrix[0])):
        tmp = []
        for i in range(len(matrix)):
            tmp.append(matrix[i][j])
        matrixT.append(tmp)

    return matrixT

In [16]:
transposition(matrix1)

[[1, 5], [2, 6], [3, 7], [4, 8]]

In [17]:
matrix3 = transposition(matrix2)

In [18]:
matrix1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
matrix2

[[11, 12, 13, 14], [15, 16, 17, 18]]

In [20]:
matrix3

[[11, 15], [12, 16], [13, 17], [14, 18]]

In [21]:
matrix4 = transposition(matrix3)
matrix4

[[11, 12, 13, 14], [15, 16, 17, 18]]

In [22]:
# numpy
np_res = np.dot(np_matrix1, np_matrix2.T)

# python
def matmul_matrix_matrix(matrix_first, matrix_second):
    result = []
    matrix_second = transposition(matrix_second)
    for i in range(len(matrix_first)):
        middle = []
        for j in range(len(matrix_second)):
            tmp = 0
            for z in range(len(matrix_first[0])):
                tmp += matrix_first[i][z] * matrix_second[j][z]
            middle.append(tmp)
        result.append(middle)
    return result

py_res = matmul_matrix_matrix(matrix1, matrix3)

print(np_res, py_res)

[[130 170]
 [330 434]] [[130, 170], [330, 434]]


**CALCULATOR**

In [23]:
def calculator(object1, object2, operation):
    """
    This function can add or multiply two scalars, vectors and matrices.
    Also, it can give a description of the error if action is not possible
    object1: scalar (int) or vector (list) or matrix (list)
    object2: scalar (int) or vector (list) or matrix (list)
    operation: type of operation (add or multiply) -> str
    return: int or list result depending on type of operation
    """

    def type_checker(object):
        """
        This functions checks type of input object: scalar/vector/matrix
        object: int or list
        return: type of object -> str, or error message
        """
        if type(object) == int:
            return "scalar"
        elif type(object) != int and type(object[0]) == int:
            return "vector"
        elif type(object) != int and type(object) != list:
            print("Wrong format")
        elif type(object) != int and type(object[0]) != int:
            return "matrix"
        else:
            return "Wrong format"

    def get_dims(object) -> list:
        """
        This function is for gettingdims of object (vector or matrix)
        object: vector or matrix -> list
        return: tuple with object's dims
        """
        if type_checker(object) == "vector":
            dims = (len(object), 1)
        elif type_checker(object) == "matrix":
            dims = (len(object), len(object[0]))
        else:
            dims = "Scalars don't have dims"
        return dims

    def transposition(matrix) -> list:
        """
        Transposition of matrix
        matrix: list
        return: transpositted matrix
        """
        matrixT = []
        for j in range(len(matrix[0])):
            tmp = []
            for i in range(len(matrix)):
                tmp.append(matrix[i][j])
            matrixT.append(tmp)
        return matrixT

    # calculation functions
    def matsum_vector_scalar(vector, scalar):
        return [v + scalar for v in vector]

    def matsum_matrix_scalar(matrix, scalar):
        return [[v + scalar for v in row] for row in matrix]

    def matsum_vector_vector(vector_first, vector_second):
        result = []
        for v_f, v_s in zip(vector_first, vector_second):
            result.append(v_f + v_s)
        return result

    def matsum_vector_matrix(vector, matrix):
        result = []
        for row in matrix:
            tmp = []
            for vec, mat in zip(vector, row):
                tmp.append(vec + mat)
            result.append(tmp)
        return result

    def matsum_matrix_matrix(matrix_first, matrix_second):
        result = []
        for i in range(len(matrix_first)):
            tmp = []
            for j in range(len(matrix_first[i])):
                tmp.append(matrix_first[i][j] + matrix_second[i][j])
            result.append(tmp)
        return result

    def matmul_vector_scalar(vector, scalar):
        return [v * scalar for v in vector]

    def matmul_matrix_scalar(matrix, scalar):
        return [[v * scalar for v in row] for row in matrix]

    def matmul_vector_vector(vector_first, vector_second):
        result = 0
        for v_f, v_s in zip(vector_first, vector_second):
            result += v_f * v_s
        return result

    def matmul_vector_matrix(matrix, vector):
        result = []
        for row in matrix:
            tmp = 0
            for m_v, v in zip(row, vector):
                tmp += m_v * v
            result.append(tmp)
        return result

    def matmul_matrix_matrix(matrix_first, matrix_second):
        result = []
        matrix_second = transposition(matrix_second)
        for i in range(len(matrix_first)):
            middle = []
            for j in range(len(matrix_second)):
                tmp = 0
                for z in range(len(matrix_first[0])):
                    tmp += matrix_first[i][z] * matrix_second[j][z]
                middle.append(tmp)
            result.append(middle)
        return result

    # main body: checks operation, and if operation is possible
    # returns final result
    if operation == "+":
        if type_checker(object1) == "scalar" and type_checker(object2) == "scalar":
            result = object1 + object2

        elif type_checker(object1) == "scalar" and type_checker(object2) == "vector":
            result = matsum_vector_scalar(object2, object1)
        elif type_checker(object1) == "vector" and type_checker(object2) == "scalar":
            result = matsum_vector_scalar(object1, object2)

        elif type_checker(object1) == "scalar" and type_checker(object2) == "matrix":
            result = matsum_matrix_scalar(object2, object1)
        elif type_checker(object1) == "matrix" and type_checker(object2) == "scalar":
            result = matsum_matrix_scalar(object1, object2)


        elif type_checker(object1) == "vector" and type_checker(object2) == "vector":
            if get_dims(object1) == get_dims(object2):
                result = matsum_vector_vector(object1, object2)
            else:
                result = "I can't add vectors with different dims"


        elif type_checker(object1) == "vector" and type_checker(object2) == "matrix":
            if get_dims(object1)[0] == get_dims(object2)[1]:
                result = matsum_vector_matrix(object1, object2)
            else:
                result = "I can't add vector and matrix with different dims"
        elif type_checker(object1) == "matrix" and type_checker(object2) == "vector":
            if get_dims(object2)[0] == get_dims(object1)[1]:
                result = matsum_vector_matrix(object2, object1)
            else:
                result = "I can't add vector and matrix with different dims"


        elif type_checker(object1) == "matrix" and type_checker(object2) == "matrix":
            if get_dims(object1) == get_dims(object2):
                result = matsum_matrix_matrix(object1, object2)
            else:
                result = "I can't add matrices with different dims"


    elif operation == "*":
        if type_checker(object1) == "scalar" and type_checker(object2) == "scalar":
            result = object1 * object2

        elif type_checker(object1) == "scalar" and type_checker(object2) == "vector":
            result = matmul_vector_scalar(object2, object1)
        elif type_checker(object1) == "vector" and type_checker(object2) == "scalar":
            result = matmul_vector_scalar(object1, object2)

        elif type_checker(object1) == "scalar" and type_checker(object2) == "matrix":
            result = matmul_matrix_scalar(object2, object1)
        elif type_checker(object1) == "matrix" and type_checker(object2) == "scalar":
            result = matmul_matrix_scalar(object1, object2)

        elif type_checker(object1) == "vector" and type_checker(object2) == "vector":
            if get_dims(object1) == get_dims(object2):
                result = matmul_vector_vector(object1, object2)
            else:
                result = "I can't multiply vectors with different dims"

        elif type_checker(object1) == "matrix" and type_checker(object2) == "vector":
            if get_dims(object1)[1] == get_dims(object2)[0]:
                result = matmul_vector_matrix(object1, object2)
            else:
                result = "I can't multiply vector and matrix with different dims"
        elif type_checker(object1) == "vector" and type_checker(object2) == "matrix":
            if get_dims(object1)[0] == get_dims(object2)[1]:
                result = f"I can multiply these vector and matrix only if change their places\n" \
                         f"{matmul_vector_matrix(object2, object1)}"
            else:
                result = "I can't multiply vector and matrix with different dims"

        elif type_checker(object1) == "matrix" and type_checker(object2) == "matrix":
            if get_dims(object1)[1] == get_dims(object2)[0]:
                result = matmul_matrix_matrix(object1, object2)
            elif get_dims(object1)[0] == get_dims(object2)[1]:
                result = f"I can multiply these matrixes only if change their places\n" \
                         f"{matmul_matrix_matrix(object2, object1)}"
            elif get_dims(object1)[1] == get_dims(object2)[1]:
                result = f"I can multiply these matrices only if transposit the second one\n" \
                         f"{matmul_matrix_matrix(object1, transposition(object2))}"
            else:
                result = "I can't multiply matrices with different dims"

        else:
           result = "Wrong format"

    else:
        result = "I don't know this operation"

    return result

In [24]:
res = np.dot(np_matrix2, np_matrix1.T)
print(res)

[[130 330]
 [170 434]]


In [25]:
mat1 = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
]
mat2 = [
    [0, 0],
    [1, 1],
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5],
    [6, 6],
    [7, 7],
    [8, 8],
    [9, 9]
]

nmat1 = np.array(mat1)
nmat2 = np.array(mat2)

In [26]:
np.dot(nmat1, nmat2)


array([[ 285,  285],
       [ 120,  120],
       [  45,   45],
       [2850, 2850]])

In [27]:
calculator(mat1, mat2, '*')

[[285, 285], [120, 120], [45, 45], [2850, 2850]]

In [28]:
calculator(mat1, mat2, '/')

"I don't know this operation"

In [29]:
np.dot(mat2, mat1)

ValueError: shapes (10,2) and (4,10) not aligned: 2 (dim 1) != 4 (dim 0)

In [30]:
print(calculator(mat2, mat1, '*'))

I can multiply these matrixes only if change their places
[[285, 285], [120, 120], [45, 45], [2850, 2850]]


In [31]:
calculator('a', mat1, '*')

Wrong format
Wrong format
Wrong format
Wrong format
Wrong format
Wrong format
Wrong format
Wrong format
Wrong format


'Wrong format'

In [32]:
calculator(1, 2, '*')

2

In [33]:
new_mat1 = []
for i in range(2):
    tmp = []
    for j in range(8):
        tmp.append(j)
    new_mat1.append(tmp)

n_mat1 = np.array(new_mat1)
new_mat1

[[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]]

In [34]:
new_mat2 = []
for i in range(8):
    tmp = []
    for j in range(2):
        tmp.append(j)
    new_mat2.append(tmp)

n_mat2 = np.array(new_mat2)
new_mat2

[[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]

In [35]:
calculator(new_mat1, new_mat2, '+')

"I can't add matrices with different dims"

In [36]:
n_mat1 + n_mat2

ValueError: operands could not be broadcast together with shapes (2,8) (8,2) 

In [37]:
calculator(new_mat1, new_mat1, '+')

[[0, 2, 4, 6, 8, 10, 12, 14], [0, 2, 4, 6, 8, 10, 12, 14]]

In [38]:
n_mat1 + n_mat1

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 0,  2,  4,  6,  8, 10, 12, 14]])

In [39]:
calculator(new_mat1, new_mat2, '*')

[[0, 28], [0, 28]]

In [40]:
np.dot(n_mat1, n_mat2)

array([[ 0, 28],
       [ 0, 28]])